"""Add universal_rules to workflows

Revision ID: 003_add_universal_rules
Revises: 002_add_extracted_variables
Create Date: 2025-08-29 02:15:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003_add_universal_rules'
down_revision = '002_add_extracted_variables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('universal_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'universal_rules')
    # ### end Alembic commands ###