/**
 * Timing pun messages for pipeline connectors.
 * {time} placeholders are replaced with the formatted delay value at runtime.
 */
export const TIMING_PUNS: Record<string, string[]> = {
  instant: [
    "⚡ Scurries out instantly",
    "⚡ Gone in a flash",
    "⚡ Sent at squirrel speed",
    "⚡ Zooms off immediately",
    "⚡ No delay, just vibes",
    "⚡ Blink and it's sent",
    "⚡ Faster than a caffeinated squirrel",
    "⚡ Instant delivery, no questions asked",
    "⚡ Launches at warp speed",
    "⚡ Already in their inbox",
    "⚡ Speed-runs the send button",
    "⚡ Hits send before you blink",
    "⚡ Turbo mode activated",
    "⚡ Zero chill, full send",
    "⚡ Practically time-travels to the inbox",
  ],
  seconds: [
    "⏰ {time} pause, then darts",
    "⏰ Holds {time}, then bolts",
    "⏰ {time} tail-twitch, then fires",
    "⏰ Counts to {time}, then whoosh",
    "⏰ A quick {time} stretch, then gone",
    "⏰ {time} deep breath, then sends",
    "⏰ Barely waits {time}, can't help it",
    "⏰ Taps paw for {time}, then goes",
    "⏰ {time} blink, then rockets off",
    "⏰ Fidgets for {time}, then launches",
    "⏰ {time} heartbeat, then delivers",
    "⏰ Quick {time} wiggle, then dashes",
    "⏰ {time} micro-nap, then zips away",
    "⏰ Sneezes after {time}, auto-sends",
    "⏰ {time} countdown, ignition, lift-off",
  ],
  minutes: [
    "⏰ {time} stretch, then sends",
    "⏰ Waits {time}, then scurries",
    "⏰ Quick {time} breather, then goes",
    "⏰ Nibbles an acorn for {time}, then fires",
    "⏰ Paces around for {time}, then delivers",
    "⏰ {time} snack break, then sends",
    "⏰ Contemplates life for {time}, then hits send",
    "⏰ Does a lap in {time}, then goes",
    "⏰ {time} warm-up jog, then sprints to inbox",
    "⏰ Stares at the sky for {time}, then sends",
    "⏰ Gathers nuts for {time}, then delivers",
    "⏰ Stretches tail for {time}, then zooms",
    "⏰ {time} meditation session, then off it goes",
    "⏰ Chews on this for {time}, then fires away",
    "⏰ {time} of anticipation, then — bam — sent",
  ],
  hours: [
    "⏰ {time} rest, then pounces",
    "⏰ Chills {time}, then sends",
    "⏰ {time} power nap, then darts",
    "⏰ Brews coffee for {time}, then delivers",
    "⏰ Takes a {time} stroll, then sends",
    "⏰ {time} of pondering, then fires",
    "⏰ Watches clouds for {time}, then hits send",
    "⏰ Lounges for {time}, then springs to action",
    "⏰ {time} siesta, then off it goes",
    "⏰ Reads a book for {time}, then delivers",
    "⏰ {time} zen garden session, then sends",
    "⏰ Naps under a tree for {time}, then goes",
    "⏰ Marinates for {time}, then serves it fresh",
    "⏰ Builds suspense for {time}, then drops it",
    "⏰ {time} beauty sleep, then dazzles the inbox",
  ],
  days: [
    "⏰ Stashed for {time}",
    "⏰ {time} nap, then pounces",
    "⏰ Sleeps {time}, then sends",
    "⏰ Ferments for {time}, then delivers",
    "⏰ {time} deep slumber, then rises",
    "⏰ Hibernates lightly for {time}, then stirs",
    "⏰ Lets it age {time}, then uncorks",
    "⏰ {time} marination period, then serves",
    "⏰ Buried like an acorn for {time}, then digs up",
    "⏰ Slow-cooked for {time}, then plated",
    "⏰ {time} patience training, then unleashes",
    "⏰ Stargazes for {time}, then fires into orbit",
    "⏰ {time} of quiet reflection, then whoosh",
    "⏰ Sits tight for {time}, then charges forward",
    "⏰ {time} incubation, then hatches into the inbox",
  ],
  weeks: [
    "⏰ Hibernates {time}, then strikes",
    "⏰ Deep stash — {time}",
    "⏰ {time} winter nap, then resurfaces",
    "⏰ Goes off-grid for {time}, then returns",
    "⏰ {time} of silence… then boom",
    "⏰ Disappears for {time}, then reappears with mail",
    "⏰ {time} sabbatical, then delivers enlightenment",
    "⏰ Meditates on a mountain for {time}, then descends",
    "⏰ Builds a nest, waits {time}, then flies out",
    "⏰ {time} slow-burn, then erupts into the inbox",
    "⏰ Crosses an ocean over {time}, then arrives",
    "⏰ {time} deep freeze, then thaws with a message",
    "⏰ Plants a seed, waits {time}, then blooms",
    "⏰ {time} long game — worth the wait",
    "⏰ Epic {time} journey, then lands in the inbox",
  ],
  ai: [
    "🧠 AI picks the moment",
    "🧠 Timed by squirrel brain",
    "🧠 AI-optimized send",
    "🧠 Neural networks decide when",
    "🧠 The algorithm knows best",
    "🧠 AI calculates the perfect moment",
    "🧠 Sent when the stars align (per AI)",
    "🧠 Machine learning says… now-ish",
    "🧠 AI consults the oracle, then sends",
    "🧠 Quantum-timed delivery",
    "🧠 AI sniffs out the best window",
    "🧠 Predictive send activated",
    "🧠 AI read the room, picked a time",
    "🧠 Timing powered by artificial wisdom",
    "🧠 The robots choose when you get mail",
  ],
}
